<a href="https://colab.research.google.com/github/iru99/pytorch_Tutorial/blob/main/pytorch_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

Tensors



*   A torch. Tensor is a multi-dimentional matrix containing elements of a single data type
*   Similar to nympy arrays, but full of fun things that make them work better on GPU's
*   default data type of float32
*   more suitable for deep learning than numpy array







In [ ]:
# List

my_list = [[1,2,3],[4,5,6]]
my_list

[[1, 2, 3], [4, 5, 6]]

In [ ]:
# Numpy Arrays

import numpy as np

np1 = np.random.rand(3,4)
np1

array([[0.50416168, 0.5393918 , 0.02368732, 0.51845392],
       [0.94150054, 0.58689496, 0.49393061, 0.95783481],
       [0.38892663, 0.82310272, 0.80694089, 0.73928522]])

In [ ]:
# Numpy data type

np1.dtype

dtype('float64')

In [ ]:
# Tensor
import torch

tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.9184,  0.2032, -0.2024,  1.8304],
        [-0.8699, -0.2068, -0.9145, -0.0799],
        [-1.0709,  0.6332, -1.2343, -1.8937]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create tensor out of numpy array

tensor = torch.tensor(np1)
tensor

tensor([[0.5042, 0.5394, 0.0237, 0.5185],
        [0.9415, 0.5869, 0.4939, 0.9578],
        [0.3889, 0.8231, 0.8069, 0.7393]], dtype=torch.float64)

torch.tensor is the page that want to use commands

In [ ]:
# Tensor Operations

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and View

my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# reshape if we dont know the number of items using -1

my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

differences between the reshape and view in pytorch

https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [ ]:
# with reshape and view, they will update

my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[1] = 20
my_torch5

tensor([ 0, 20,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
my_torch6

# when you made changes they will automatically update in reshape and view

tensor([[ 0, 20,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

**Slices**

In [ ]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# grab a specific item
my_torch7[6]

tensor(6)

In [ ]:
# Grab a slice

my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
# return a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])