<a href="https://colab.research.google.com/github/iru99/pytorch_Tutorial/blob/main/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor Math Operation**

1) Add, Substract, Multiply, Devide, Reminders, Exponents
2) Shorthand and uh, longhand
3) Reassignment

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition longhand using .add

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
# substract

tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
# .sub function

torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [8]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
# .mul function

torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
# .dev function

torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [14]:
# .reminder function

torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [15]:
# Expornents / Power

torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [16]:
# Another way to write

tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [17]:
# Reassignment

tensor_a = tensor_a + tensor_b
tensor_a

tensor([ 6,  8, 10, 12])

In [18]:
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [19]:
tensor_a

tensor([11, 14, 17, 20])